### ISSUE TITLE
Error: The .mtd file is corrupt. Start a new download?? 

### ISSUE THREAD

**Issue by renjithaccel** [leeroybrun/node-mt-files-downloader#14]
Hi,

I'm getting this error while running the sample download scripts. I saw an .mtd file is creating on my destination directory. After few seconds it is failing. The error is

Error: The .mtd file is corrupt. Start a new download.
at module.exports (/home/testmachine/node_modules/mt-downloader/lib/Exceptions.js:83:33)
at /home/testmachine/node_modules/mt-downloader/lib/core/DownloadReaderAsyncTask.js:36:13
at FSReqWrap.wrapper [as oncomplete] (fs.js:602:17)

**Comment by pantchox** [comment]
this happend to me when i did not have enough disk space.
also i have a hunch it might be realted to IO non handled issues by this module, for example your destination filename directory might night exist.

**Comment by tadeork** [comment]
Maybe it's because you're trying to download from a https url?

**Comment by VladimirMerk** [comment]
Exactly the same problem on ubuntu 16.
I load in /tmp, it creates a mtd file with size 0 bytes

`EVENT - Download error !
Error: The .mtd file is corrupt. Start a new download.
    at module.exports (./node_modules/mt-files-downloader/node_modules/mt-downloader/lib/Exceptions.js:83:33)
    at ./node_modules/mt-files-downloader/node_modules/mt-downloader/lib/core/DownloadReaderAsyncTask.js:36:13
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)`

**Comment by alimpaecher** [comment]
I also received the .mtd file is corrupt error. Mine was caused by the fact that the download source location was incorrect (and so the file did not exist).
