### ISSUE TITLE
Error using with Electron JS

### ISSUE THREAD

**Issue by mytc** [leeroybrun/node-mt-files-downloader#9]
I don't if this package is compatible with Electron js or not. But I give it a try anyway. 
And I got this error:

```
Uncaught Exception:
Error: Uncaught, unspecified "error" event. ([object Object])
    at Download.emit (events.js:163:17)
    at options.onEnd (/....../node_modules/mt-files-downloader/lib/Download.js:308:18)
    at taskCallback (/....../node_modules/mt-downloader/node_modules/async/lib/async.js:443:21)
    at /....../node_modules/mt-downloader/lib/core/DownloadReaderAsyncTask.js:36:4
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

Any ideal why?

**Comment by tadeork** [comment]
How did you solved this?
